version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: telcox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telcox_db
      MYSQL_USER: telcox
      MYSQL_PASSWORD: telcox123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - telcox-network

  backend:
    build:
      context: ./backend
    container_name: telcox-backend
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - telcox-network
    # Evita race conditions
    command: >
      sh -c "sleep 5 && python wsgi.py"

  frontend:
    build:
      context: ./frontend
    container_name: telcox-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - telcox-network

volumes:
  db_data:

networks:
  telcox-network:
    driver: bridge
